/**
 * Murmur Agent — Core Types
 *
 * This module defines all TypeScript interfaces used throughout the murmur-agent
 * codebase: configuration schemas, thought structures, the knowledge tensor,
 * budget tracking state, and thought clustering/contradiction models.
 *
 * The DEFAULT_CONFIG export provides sensible defaults for all settings,
 * allowing agents to run with zero configuration (provider: 'none',
 * 50 max thoughts, markdown output).
 */

/**
 * Top-level configuration for a Murmur thinking session.
 * Each sub-config controls a different aspect: context ingestion,
 * thinking behavior, output formatting, and API budget management.
 */
export interface MurmurConfig {
  topic: string;
  context: ContextConfig;
  thinking: ThinkingConfig;
  output: OutputConfig;
  budget: BudgetConfig;
}

/**
 * Configuration for what project files to ingest as context.
 * Controls which files are read to provide domain knowledge
 * for the thinking strategies.
 */
export interface ContextConfig {
  includePatterns: string[];
  excludePatterns: string[];
  maxFiles: number;
  maxTokensPerFile: number;
}

/**
 * Configuration for how the Thinker generates thoughts.
 * Controls timing, depth, which strategies to use, and when to stop.
 */
export interface ThinkingConfig {
  /** Seconds between thoughts (0 for batch mode) */
  interval: number;
  /** Maximum number of thoughts before stopping */
  maxThoughts: number;
  /** Thinking depth: affects output verbosity and strategy complexity */
  depth: 'shallow' | 'medium' | 'deep';
  /** Ordered list of strategies to cycle through */
  strategies: ThinkingStrategy[];
}

/**
 * The five thinking strategies Murmur uses to explore idea spaces.
 *
 * - explore:    Breadth-first search for new angles and unexplored perspectives
 * - connect:    Find bridges between existing thoughts and concepts
 * - contradict: Stress-test assumptions by surfacing tensions and paradoxes
 * - synthesize: Identify recurring themes and emerging patterns
 * - question:   Meta-cognitive checks to ensure we're asking the right questions
 */
export type ThinkingStrategy = 'explore' | 'connect' | 'contradict' | 'synthesize' | 'question';

/**
 * Configuration for where and how thoughts are persisted to disk.
 * Supports markdown, JSON, or both formats simultaneously.
 */
export interface OutputConfig {
  directory: string;
  format: 'markdown' | 'json' | 'both';
  autoSummary: boolean;
  commitEachThought: boolean;
}

/**
 * Configuration for API budget management.
 * Supports multiple LLM providers and two budget strategies:
 * - 'accumulate': unused daily calls roll over to the next day
 * - 'reset': fresh daily budget, unused calls are lost
 */
export interface BudgetConfig {
  provider: 'openai' | 'anthropic' | 'ollama' | 'local' | 'none';
  apiKey?: string;
  baseURL?: string;
  model?: string;
  maxCallsPerDay: number;
  budgetStrategy: 'accumulate' | 'reset';
}

/**
 * A single thought generated by the Thinker.
 * Each thought is produced by one strategy and captures content,
 * connections to prior topics, open questions, and a confidence score.
 */
export interface Thought {
  id: number;
  timestamp: string;
  strategy: ThinkingStrategy;
  topic: string;
  content: string;
  connections: string[];
  questions: string[];
  confidence: number;
  tokensUsed: number;
}

/**
 * The evolving knowledge structure at the heart of Murmur.
 * Grows with every thought — tracks all thoughts, clusters them
 * by theme, records contradictions, and collects open questions.
 * Serialized as tensor.json after each thought cycle.
 */
export interface KnowledgeTensor {
  topic: string;
  thoughts: Thought[];
  clusters: ThoughtCluster[];
  contradictions: Contradiction[];
  openQuestions: string[];
  totalTokens: number;
  startedAt: string;
  lastUpdatedAt: string;
}

/**
 * A group of related thoughts identified by clustering.
 * Clusters emerge as the knowledge tensor grows and patterns repeat.
 */
export interface ThoughtCluster {
  id: string;
  label: string;
  thoughtIds: number[];
  summary: string;
}

/**
 * A detected tension between two thoughts.
 * Contradictions are identified by the 'contradict' strategy and
 * can optionally be resolved by later synthesis.
 */
export interface Contradiction {
  thoughtA: number;
  thoughtB: number;
  description: string;
  resolution?: string;
}

/**
 * Snapshot of the current API budget usage.
 * Tracks both daily and cumulative call/token counts,
 * enabling the 'accumulate' budget strategy to function.
 */
export interface BudgetState {
  callsToday: number;
  callsTotal: number;
  tokensToday: number;
  tokensTotal: number;
  lastCallAt: string | null;
  budgetDate: string;
}

export const DEFAULT_CONFIG: MurmurConfig = {
  topic: 'general exploration',
  context: {
    includePatterns: ['**/*.ts', '**/*.md', '**/*.py'],
    excludePatterns: ['node_modules/**', '.git/**', 'dist/**'],
    maxFiles: 50,
    maxTokensPerFile: 2000,
  },
  thinking: {
    interval: 60,
    maxThoughts: 50,
    depth: 'medium',
    strategies: ['explore', 'connect', 'contradict', 'synthesize', 'question'],
  },
  output: {
    directory: 'murmur-output',
    format: 'markdown',
    autoSummary: true,
    commitEachThought: true,
  },
  budget: {
    provider: 'none',
    maxCallsPerDay: 50,
    budgetStrategy: 'accumulate',
  },
};
